import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { TRPCProvider } from '@/lib/trpc/provider'
import Navigation from '../components/Navigation'
import '@/app/globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='pl-PL'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased ms-nav-width relative`}>
				<div className='max-w-[1200px]'>
					<TRPCProvider>
						<Navigation />
						{children}
					</TRPCProvider>
				</div>
			</body>
		</html>
	)
}
