import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import { supabase } from '@/lib/supabase/client'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<nav>
					<form
						action={async () => {
							'use server'
							await supabase.auth.signOut()
						}}>
						<button className='bg-white p-4 text-black'>Log out</button>
					</form>
				</nav>
				{children}
			</body>
		</html>
	)
}
